"""Deterministic Moroccan-PCG accounting engine.

Key safety rules:
- one legal-entity perspective is generated by default (buyer; sales invoices may
  explicitly request seller), never both as the production default;
- invoice payment wording does not create settlement entries;
- mixed-rate VAT is computed from the actual line bases/rates;
- account selection follows explicit accounting nature rather than treating every
  non-asset item as a generic service.
"""
from __future__ import annotations

from datetime import date
from decimal import Decimal, ROUND_HALF_UP

from app.core.logging import logger
from app.models.invoice import (
    CalculationBreakdown,
    ExtractedInvoiceData,
    JournalEntry,
    JournalLine,
    PaymentStatusInfo,
)
from app.services import accounts as acct
from app.services.accounts import (
    CLIENT_ACCOUNT,
    DROITS_DE_TIMBRE_ACCOUNT,
    ESCOMPTE_ACCORDE,
    ESCOMPTE_OBTENU,
)
from app.services.dates import parse_iso

CENT = Decimal("0.01")


def _d(value) -> Decimal:
    return Decimal(str(value or 0))


def _q(value: Decimal) -> Decimal:
    return value.quantize(CENT, rounding=ROUND_HALF_UP)


def r2(value: float | Decimal) -> float:
    return float(_q(_d(value)))


def _line_vat_total(data: ExtractedInvoiceData, net_financier_ht: Decimal, montant_brut: Decimal) -> Decimal:
    """VAT from line-level bases. Discounts/escompte are spread proportionally.

    Each line is rounded to centimes independently; no line is allowed to absorb
    a material residual merely to force agreement with an invoice-level rate.
    """
    if not data.line_items or montant_brut == 0:
        return _q(net_financier_ht * _d(data.tva_pct) / Decimal(100))
    factor = net_financier_ht / montant_brut
    total = Decimal(0)
    for line in data.line_items:
        base = _d(line.line_total_ht) * factor
        total += _q(base * _d(line.tva_rate) / Decimal(100))
    return _q(total)


def _applicable_stamp_duty(data: ExtractedInvoiceData) -> Decimal:
    """Resolve conditional stamp duty from explicit document evidence only."""
    condition = (data.droits_de_timbre_condition or "").strip().casefold()
    if not condition:
        return _q(_d(data.droits_de_timbre))

    cash_condition = any(marker in condition for marker in ("espèce", "espece", "cash"))
    if cash_condition and data.payment_mode == "caisse":
        amount = data.droits_de_timbre or data.droits_de_timbre_mentionne
        return _q(_d(amount))

    # An unmet or unprovable condition must never increase the payable amount.
    return Decimal(0)


def compute_invoice(data: ExtractedInvoiceData) -> CalculationBreakdown:
    """Apply brut -> commercial discounts -> escompte -> VAT -> withholding/timbre.

    Decimal is used for accounting arithmetic; API compatibility remains floats.
    """
    mb = _q(_d(data.montant_brut))
    rabais_amount = _q(mb * _d(data.rabais_pct) / Decimal(100)) if data.rabais_pct > 0 else Decimal(0)
    net1 = _q(mb - rabais_amount)
    remise_amount = _q(net1 * _d(data.remise_pct) / Decimal(100)) if data.remise_pct > 0 else Decimal(0)
    net2 = _q(net1 - remise_amount)
    ristourne_amount = _q(net2 * _d(data.ristourne_pct) / Decimal(100)) if data.ristourne_pct > 0 else Decimal(0)
    net_commercial = _q(net2 - ristourne_amount)
    escompte_amount = _q(net_commercial * _d(data.escompte_pct) / Decimal(100)) if data.escompte_pct > 0 else Decimal(0)
    net_financier_ht = _q(net_commercial - escompte_amount)
    tva_amount = _line_vat_total(data, net_financier_ht, mb)
    ttc = _q(net_financier_ht + tva_amount)
    if data.retenue_a_la_source_pct > 0:
        if data.withholding_type == "vat_withholding":
            withholding_base = tva_amount
        elif data.withholding_base == "ttc":
            withholding_base = ttc
        elif data.withholding_base == "tva_amount":
            withholding_base = tva_amount
        else:
            withholding_base = net_financier_ht
        ras_amount = _q(withholding_base * _d(data.retenue_a_la_source_pct) / Decimal(100))
    else:
        ras_amount = Decimal(0)
    timbre = _applicable_stamp_duty(data)
    net_a_payer = _q(ttc - ras_amount + timbre)
    return CalculationBreakdown(
        montant_brut=float(mb), rabais_pct=data.rabais_pct, rabais_amount=float(rabais_amount), net1=float(net1),
        remise_pct=data.remise_pct, remise_amount=float(remise_amount), net2=float(net2),
        ristourne_pct=data.ristourne_pct, ristourne_amount=float(ristourne_amount), net_commercial=float(net_commercial),
        escompte_pct=data.escompte_pct, escompte_amount=float(escompte_amount), net_financier_ht=float(net_financier_ht),
        tva_pct=data.tva_pct, tva_amount=float(tva_amount), ttc=float(ttc),
        retenue_a_la_source_pct=data.retenue_a_la_source_pct,
        retenue_a_la_source_amount=float(ras_amount), droits_de_timbre=float(timbre), net_a_payer=float(net_a_payer),
    )


def determine_payment_status(data: ExtractedInvoiceData, calc: CalculationBreakdown) -> PaymentStatusInfo:
    """Invoice wording never proves payment; actual status comes from allocations.

    The static pipeline status is therefore UNPAID/OVERDUE.  The persisted API
    later overlays bank-reconciliation allocations to support partial/full payment.
    """
    due = parse_iso(data.due_date)
    status = "OVERDUE" if due and due < date.today() else "UNPAID"
    return PaymentStatusInfo(
        status=status,
        due_date=data.due_date or "Non precisee",
        amount_outstanding=calc.net_a_payer,
    )


async def group_multiline_items(data: ExtractedInvoiceData) -> dict:
    """Group line items by account + VAT rate + asset/charge route."""
    grouped: dict = {}
    for line in data.line_items:
        if line.is_immobilisation:
            code, label = await acct.immobilisation_account(line.immobilisation_type)
            group_type = "asset"
            nature = line.immobilisation_type or "other"
        else:
            nature = line.accounting_nature
            if nature == "unclassified" and data.invoice_category == "facture_achat":
                nature = "merchandise"
            code, label = await acct.purchase_account_for_nature(nature)
            group_type = "charge"
        composite_key = f"{code}::{line.tva_rate}::{group_type}"
        if composite_key not in grouped:
            grouped[composite_key] = {
                "account": code, "label": label, "total_ht": 0.0,
                "tva_rate": line.tva_rate, "group_type": group_type, "nature": nature,
            }
        grouped[composite_key]["total_ht"] += line.line_total_ht
    return grouped


def _split_multiline_tva(multiline_groups: dict, ht_factor: float = 1.0) -> tuple[float, float]:
    """Compute each group's VAT independently and route 34551 vs 34552."""
    tva_to_assets = Decimal(0)
    tva_to_charges = Decimal(0)
    factor = _d(ht_factor)
    for group in multiline_groups.values():
        vat = _q(_d(group["total_ht"]) * factor * _d(group["tva_rate"]) / Decimal(100))
        if group["group_type"] == "asset":
            tva_to_assets += vat
        else:
            tva_to_charges += vat
    return float(_q(tva_to_assets)), float(_q(tva_to_charges))


def _rrr_accounts(data: ExtractedInvoiceData) -> tuple[tuple[str, str], tuple[str, str]]:
    """Seller/buyer accounts for post-invoice commercial discounts."""
    service = data.invoice_category == "facture_service" or data.accounting_nature in {
        "rent", "maintenance", "insurance", "professional_fees", "studies_documentation",
        "transport", "advertising", "telecom", "banking_services", "royalties", "other_external_service",
    }
    seller = ("71294", "R.R.R. accordés sur ventes au Maroc des services produits") if service else ("7119", "Rabais, remises et ristournes accordés")
    if service:
        buyer = ("6149", "R.R.R. obtenus sur autres charges externes")
    elif data.accounting_nature in {"raw_material", "consumable_supplies", "nonstocked_supplies"}:
        buyer = ("6129", "Rabais, remises et ristournes obtenus sur achats consommés")
    else:
        buyer = ("6119", "Rabais, remises et ristournes obtenus sur achats de marchandises")
    return seller, buyer


async def generate_journal_entries(data: ExtractedInvoiceData, calc: CalculationBreakdown) -> list[JournalEntry]:
    entries: list[JournalEntry] = []
    d = data.date or "Non precisee"
    n = data.invoice_number or "XX"
    ca, cl = CLIENT_ACCOUNT
    esc = calc.escompte_amount > 0
    tva = calc.tva_amount > 0
    # Legacy 'both' remains viewable but is never the default and posting selects one owner.
    skip_seller = data.requested_perspective == "buyer"
    skip_buyer = data.requested_perspective == "seller"
    rev_acct, rev_label, pur_acct, pur_label = await acct.revenue_purchase_accounts(data)
    is_service = data.invoice_category == "facture_service"

    is_multiline = bool(data.line_items)
    multiline_groups = await group_multiline_items(data) if is_multiline else {}
    if is_multiline:
        logger.info("Multi-line invoice detected", num_lines=len(data.line_items), num_groups=len(multiline_groups))

    tva_seller_acct, tva_label_seller = await acct.seller_tva_account()
    tva_charge_acct, tva_label_buyer_charges = await acct.tva_charge_account()
    tva_asset_acct, tva_label_buyer_assets = await acct.tva_asset_account()
    fournisseur_acct, fournisseur_label = await acct.fournisseur_account()
    if data.retenue_a_la_source_pct > 0 and data.withholding_type not in (None, "cit_iit"):
        ras_acct = data.withholding_account_number or "3497"
        ras_label = "Retenue fiscale à valider" if ras_acct == "3497" else "Retenue fiscale selon règle approuvée"
    else:
        ras_acct, ras_label = await acct.ras_account()

    goods_factor = 1.0
    tva_ht_factor = 1.0
    if is_multiline and calc.montant_brut > 0:
        goods_factor = calc.net_commercial / calc.montant_brut
        tva_ht_factor = calc.net_financier_ht / calc.montant_brut

    def buyer_tva_lines(side: str) -> list[JournalLine]:
        if not tva:
            return []
        if is_multiline:
            assets, charges = _split_multiline_tva(multiline_groups, tva_ht_factor)
            lines: list[JournalLine] = []
            if assets:
                lines.append(JournalLine(side=side, account_number=tva_asset_acct, account_label=tva_label_buyer_assets, amount=assets))
            if charges:
                lines.append(JournalLine(side=side, account_number=tva_charge_acct, account_label=tva_label_buyer_charges, amount=charges))
            return lines
        target = (tva_asset_acct, tva_label_buyer_assets) if data.is_immobilisation else (tva_charge_acct, tva_label_buyer_charges)
        return [JournalLine(side=side, account_number=target[0], account_label=target[1], amount=calc.tva_amount)]

    def buyer_goods_lines(side: str, *, rrr: bool = False) -> list[JournalLine]:
        if rrr:
            _, buyer_rrr = _rrr_accounts(data)
            return [JournalLine(side=side, account_number=buyer_rrr[0], account_label=buyer_rrr[1], amount=calc.net_commercial)]
        if not is_multiline:
            return [JournalLine(side=side, account_number=pur_acct, account_label=pur_label, amount=calc.net_commercial)]
        groups = list(multiline_groups.values())
        lines: list[JournalLine] = []
        running = Decimal(0)
        for g in groups[:-1]:
            amount = _q(_d(g["total_ht"]) * _d(goods_factor))
            running += amount
            lines.append(JournalLine(side=side, account_number=g["account"], account_label=g["label"], amount=float(amount)))
        last_amount = _q(_d(calc.net_commercial) - running)
        g = groups[-1]
        lines.append(JournalLine(side=side, account_number=g["account"], account_label=g["label"], amount=float(last_amount)))
        return lines

    if data.invoice_type == "DOIT":
        if not skip_seller:
            sl: list[JournalLine] = []
            if esc:
                sl.append(JournalLine(side="DEBIT", account_number=ESCOMPTE_ACCORDE[0], account_label=ESCOMPTE_ACCORDE[1], amount=calc.escompte_amount))
            sl.append(JournalLine(side="DEBIT", account_number=ca, account_label=cl, amount=calc.ttc))
            sl.append(JournalLine(side="CREDIT", account_number=rev_acct, account_label=rev_label, amount=calc.net_commercial))
            if tva:
                sl.append(JournalLine(side="CREDIT", account_number=tva_seller_acct, account_label=tva_label_seller, amount=calc.tva_amount))
            entries.append(JournalEntry(perspective="Seller", date=d, libelle=f"Facture n {n} — {'prestation de services' if is_service else 'vente'}", lines=sl))

        if not skip_buyer:
            bl = buyer_goods_lines("DEBIT") + buyer_tva_lines("DEBIT")
            if esc:
                bl.append(JournalLine(side="CREDIT", account_number=ESCOMPTE_OBTENU[0], account_label=ESCOMPTE_OBTENU[1], amount=calc.escompte_amount))
            fournisseur_amount = r2(calc.ttc - calc.retenue_a_la_source_amount + calc.droits_de_timbre)
            bl.append(JournalLine(side="CREDIT", account_number=fournisseur_acct, account_label=fournisseur_label, amount=fournisseur_amount))
            if calc.retenue_a_la_source_amount > 0:
                bl.append(JournalLine(side="CREDIT", account_number=ras_acct, account_label=ras_label, amount=calc.retenue_a_la_source_amount))
            if calc.droits_de_timbre > 0:
                bl.append(JournalLine(side="DEBIT", account_number=DROITS_DE_TIMBRE_ACCOUNT[0], account_label=DROITS_DE_TIMBRE_ACCOUNT[1], amount=calc.droits_de_timbre))
            entries.append(JournalEntry(perspective="Buyer", date=d, libelle=f"Facture n {n} — {'prestation de services' if is_service else 'achat'}", lines=bl))

    else:  # AVOIR
        is_rrr = data.credit_note_reason == "post_invoice_discount"
        seller_rrr, _ = _rrr_accounts(data)
        if not skip_seller:
            sl: list[JournalLine] = []
            seller_account = seller_rrr if is_rrr else (rev_acct, rev_label)
            sl.append(JournalLine(side="DEBIT", account_number=seller_account[0], account_label=seller_account[1], amount=calc.net_commercial))
            if tva:
                sl.append(JournalLine(side="DEBIT", account_number=tva_seller_acct, account_label=tva_label_seller, amount=calc.tva_amount))
            if esc:
                # Reverse the original debit 6386.
                sl.append(JournalLine(side="CREDIT", account_number=ESCOMPTE_ACCORDE[0], account_label=ESCOMPTE_ACCORDE[1], amount=calc.escompte_amount))
            sl.append(JournalLine(side="CREDIT", account_number=ca, account_label=cl, amount=calc.ttc))
            entries.append(JournalEntry(perspective="Seller", date=d, libelle=f"Avoir n {n}", lines=sl))

        if not skip_buyer:
            bl: list[JournalLine] = []
            fournisseur_amount = r2(calc.ttc - calc.retenue_a_la_source_amount + calc.droits_de_timbre)
            bl.append(JournalLine(side="DEBIT", account_number=fournisseur_acct, account_label=fournisseur_label, amount=fournisseur_amount))
            if calc.retenue_a_la_source_amount > 0:
                bl.append(JournalLine(side="DEBIT", account_number=ras_acct, account_label=ras_label, amount=calc.retenue_a_la_source_amount))
            if esc:
                # Reverse the original credit 7386.
                bl.append(JournalLine(side="DEBIT", account_number=ESCOMPTE_OBTENU[0], account_label=ESCOMPTE_OBTENU[1], amount=calc.escompte_amount))
            bl.extend(buyer_goods_lines("CREDIT", rrr=is_rrr))
            bl.extend(buyer_tva_lines("CREDIT"))
            if calc.droits_de_timbre > 0:
                bl.append(JournalLine(side="CREDIT", account_number=DROITS_DE_TIMBRE_ACCOUNT[0], account_label=DROITS_DE_TIMBRE_ACCOUNT[1], amount=calc.droits_de_timbre))
            entries.append(JournalEntry(perspective="Buyer", date=d, libelle=f"Avoir n {n}", lines=bl))

    # No settlement entries here. Payment/settlement is recognized only from
    # bank/cash evidence and allocations in the treasury module.
    return entries
